CREATE TABLE [dbo].[TBCONDUTOR] (
    [ID]         INT           IDENTITY (1, 1) NOT NULL,
    [NOME]       VARCHAR (70)  NOT NULL,
    [ENDERECO]   VARCHAR (100) NOT NULL,
    [CPF]        VARCHAR (70)  NOT NULL,
    [CNH]        VARCHAR (70)  NOT NULL,
    [EMAIL]      VARCHAR (70)  NOT NULL,
    [CLIENTE_ID] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TBCONDUTOR_ToTBCLIENTE] FOREIGN KEY ([CLIENTE_ID]) REFERENCES [dbo].[TBCliente] ([Id])
);

