CREATE TABLE [DBO].[TBCONDUTOR]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NOME] VARCHAR(70) NOT NULL, 
    [ENDERECO] VARCHAR(100) NOT NULL, 
    [CPF] VARCHAR(70) NOT NULL, 
    [CNH] VARCHAR(70) NOT NULL, 
    [EMAIL] VARCHAR(70) NOT NULL, 
    [CLIENTE_ID] INT NOT NULL, 
    CONSTRAINT [FK_TBCONDUTOR_ToTBCLIENTE] FOREIGN KEY (CLIENTE_ID) REFERENCES [TBCLIENTE]([ID])
)
