CREATE TABLE [dbo].[TBCONDUTOR] (
    [id]         UNIQUEIDENTIFIER NOT NULL,
    [NOME]       VARCHAR (70)     NOT NULL,
    [ENDERECO]   VARCHAR (100)    NOT NULL,
    [CPF]        VARCHAR (70)     NOT NULL,
    [CNH]        VARCHAR (70)     NOT NULL,
    [EMAIL]      VARCHAR (70)     NOT NULL,
    [CLIENTE_ID] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_TBCONDUTOR] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_TBCONDUTOR_ToTBCLIENTE] FOREIGN KEY ([CLIENTE_ID]) REFERENCES [dbo].[TBCliente] ([id])
);

